# Generated by Django 3.2.7 on 2021-10-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('giveaways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('narration', models.CharField(max_length=100, verbose_name='narration')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=11, verbose_name='amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=8, verbose_name='transaction status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='giveaways.giveaway')),
            ],
        ),
    ]
