# Generated by Django 3.2.7 on 2021-10-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_change_default_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gateway_response',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='gateway response'),
        ),
    ]
