# Generated by Django 3.2.7 on 2021-10-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_gateway_response_column_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('REVERSED', 'Reversed'), ('FAILED', 'Failed')], default='INITIATED', max_length=15, verbose_name='transaction status'),
        ),
    ]
