# Generated by Django 3.2.7 on 2021-10-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0004_remove_constraint_on_participant_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='recipient_code',
            field=models.CharField(max_length=40, null=True, verbose_name='recipient code'),
        ),
    ]
